name: Build and Deploy Static Website

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go build -o site-generator .
      - run: mkdir site
      - run: cp -r assets site
      - run: ./site-generator

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Tailwind CSS v4 CLI
        run: npm install tailwindcss @tailwindcss/typography @tailwindcss/cli --no-save

      - name: Build Tailwind CSS
        run: |
          npx @tailwindcss/cli -i ./input.css -o ./site/assets/css/output2.css --minify

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
